version: '3'

services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"

  tzfserver:
    image: tzfserver
    volumes:
      - ./LoginWeb:/app/LoginWeb
      - ./LoginWeb/database.db:/app/database.db
    labels:
      - "traefik.frontend.rule=Host:127.0.0.1"
      - "traefik.port=5000"
      - "traefik.enable=true"
      - "traefik.backend=tzfserver"

