version: '3'
services:
  traefik:
    image: traefik
    command: --logLevel=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/host.cert:/host.cert
      - ./traefik/host.key:/host.key
    ports:
      - "80:80"
      - "443:443" # 8888:443
      - "8080:8080"
    networks:
      - mynet

  tzfserver:
    image: linnil1/tzfserver
    command: "gunicorn tzfserver:app -b 0.0.0.0:5000 --access-logfile /app/LoginWeb/log --reload"
    # command: "flask run -h 0.0.0.0"
    # environment:
    #   - FLASK_DEBUG=1
    #   - FLASK_APP=tzfserver
    volumes:
      - ./LoginWeb:/app/LoginWeb
      - ./LoginWeb/database.db:/app/database.db
      - /var/run/DockerServer:/app/sock
    labels:
      - "traefik.frontend.rule=Host:127.0.0.1"
      - "traefik.port=5000"
      - "traefik.enable=true"
      - "traefik.backend=tzfserver"
      # - "traefik.frontend.entryPoints=https" # not work
    networks:
      - mynet

  dockerserver:
    image: linnil1/dockerserver
    command: "gunicorn -b unix:///app/sock/DockerServer.sock DockerServer:app --reload"
    volumes:
      - ./DockerServer:/app/DockerServer
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/DockerServer:/app/sock
    labels:
      - "traefik.enable=false"
    networks:
      - mynet

  vnc:
    image: linnil1/docker-vnc
    volumes:
      - ./my_vnc:/app/my_vnc
      - ./LoginWeb/database.db:/app/database.db
    labels:
      - "traefik.frontend.rule=Host:127.0.0.1;PathPrefixStrip:/vnc"
      - "traefik.port=6080"
      - "traefik.enable=true"
      - "traefik.backend=vnc"
      - "traefik.frontend.entryPoints=https"
    networks:
      - mynet

  dock:
    image: docker-firefox
    command: "x11vnc -forever -usepw -create"
    networks:
      - mynet

  idp:
    image: linnil1/idp
    command: "python idp.py"
    volumes:
      - ./IDP:/app/IDP
      - ./LoginWeb/database.db:/app/database.db
    labels:
      - "traefik.frontend.rule=Host:my.domain.ntu.edu.tw;PathPrefixStrip:/saml/"
      - "traefik.port=8088"
      - "traefik.enable=true"
      - "traefik.backend=idp"
    networks:
      - mynet

  nextcloud:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./Nextcloud/nextcloud:/var/www/html
      - ./Nextcloud/etcpasswd:/etc/passwd
      - ./Nextcloud/etcgroup:/etc/group
      - /home/your_external/:/external_data
    networks:
      - mynet

  nextcloud_web:
    image: nginx
    restart: always
    ports:
      - 8888:443
    external_links:
      - nextcloud
      - collabora
    volumes:
      - ./Nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Nextcloud/nextcloud:/var/www/html
      - ./Nextcloud/certs:/certs
      - ./Nextcloud/log:/var/log/nginx/
    depends_on:
      - nextcloud
      - collabora
    networks:
      - mynet

  collabora:
    image: collabora/code
    restart: always
    cap_add:
      - MKNOD
    environment:
      - domain=my.domain.ntu.edu.tw
    networks:
      - mynet

networks:
  mynet:
    # external:
    #   name: my-pre-existing-network
    # and comment out below
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
