version: '3'
services:
  traefik:
    image: traefik
    restart: always
    command: --logLevel=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./certs:/certs
    ports:
      - "80:80"
      - "443:443" # 8888:443
      - "8080:8080"
    networks:
      - mynet

  oauthserver:
    image: linnil1/oauthserver
    restart: always
    command: "gunicorn -b 0.0.0.0:5000 app:app --access-logfile /app/OauthServer/access.log"
    volumes:
      - ./OauthServer:/app/OauthServer
    labels:
      - "traefik.frontend.rule=Host:127.0.0.1"
      - "traefik.port=5000"
      - "traefik.enable=true"
      - "traefik.backend=oauthserver"
    depends_on:
      - dockerserver 
    external_links:
      - dockerserver:dockerserver 
    networks:
      - mynet

  vnc:
    image: linnil1/docker-vnc
    restart: always
    volumes:
      - ./my_vnc:/app/my_vnc
      - ./OauthServer/db.sqlite:/app/db.sqlite:ro
    labels:
      - "traefik.frontend.rule=Host:127.0.0.1;PathPrefixStrip:/vnc/"
      - "traefik.port=6080"
      - "traefik.enable=true"
      - "traefik.backend=vnc"
    networks:
      - mynet

  dockerserver:
    restart: always
    image: linnil1/dockerserver
    command: "gunicorn -b 0.0.0.0:3476 DockerServer:app"
    volumes:
      - ./DockerServer:/app/DockerServer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"
    networks:
      - mynet

  guikill:
    image: linnil1/dockerserver
    command: "python3 /app/guikill.py"
    volumes:
      - ./DockerServer:/app/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"
    networks:
      - mynet

  test:
    image: docker-firefox
    command: "x11vnc -forever -usepw -create"
    networks:
      - mynet

  nextcloud:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./Nextcloud/nextcloud:/var/www/html
      - ./Nextcloud/etcpasswd:/etc/passwd
      - ./Nextcloud/etcgroup:/etc/group
      - /path/external_data:/external_data
    depends_on:
      - nextcloud_db
    external_links:
      - nextcloud_db:nextclouddb
    networks:
      - mynet

  nextcloud_web:
    image: nginx
    restart: always
    ports:
      - 8888:443
    external_links:
      - nextcloud
      - collabora
    volumes:
      - ./certs:/certs
      - ./Nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Nextcloud/nextcloud:/var/www/html
      - ./Nextcloud/log:/var/log/nginx/
    depends_on:
      - nextcloud
      - collabora
    networks:
      - mynet

  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - ./Nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - mynet

  collabora:
    image: collabora/code
    restart: always
    cap_add:
      - MKNOD
    environment:
      - domain=my.domain.ntu.edu.tw
    networks:
      - mynet

networks:
  mynet:
    # external:
    #   name: my-pre-existing-network
    # and comment out below
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
