version: '3'

services:
  app:  
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./nextcloud:/var/www/html

  web:
    image: nginx
    restart: always
    ports:
      - 443:443
    external_links:
      - app
      - collabora
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud:/var/www/html
      - ./certs:/certs
      - ./log:/var/log/nginx/

    depends_on:
      - app
      - collabora

  collabora:
    image: collabora/code
    restart: always
    cap_add:
      - MKNOD
    environment:
      - domain=xx.ntu.edu.tw
    # volumes:
    #   - ./collabora:/etc/loolwsd
