apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.protocol: https
spec:
  rules:
  - http:
      paths:
      - path: /drive/
        backend:
          serviceName: nextcloud-nginx
          servicePort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vnc
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /vnc/
        backend:
          serviceName: novnc
          servicePort: 6080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: labboxmain
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: labboxmain
          servicePort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: collabora
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /lool/
        backend:
          serviceName: nextcloud-nginx
          servicePort: 443
      - path: /loleaflet/
        backend:
          serviceName: nextcloud-nginx
          servicePort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud-dav
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-regex: https://(.*)/.well-known/(card|cal)dav
    traefik.ingress.kubernetes.io/redirect-replacement: https://$1/drive/remote.php/dav/
spec:
  rules:
  - http:
      paths:
      - path: /.well-known/
        backend:
          serviceName: nextcloud-nginx
          servicePort: 443
---
