---
apiVersion: v1
kind: Service
metadata:
  name: myvnc-web
spec:
  selector:
    name: myvnc-pod
  ports:
  - port: 6080
    targetPort: 6080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvnc-dep
spec:
  selector:
    matchLabels:
      name: myvnc-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: myvnc-pod
    spec:
      containers:
      - name: myvnc
        image: registry-svc.default.svc.cluster.local:5002/linnil1/docker-vnc
        ports:
        - containerPort: 6080
          protocol: TCP
        volumeMounts:
        - name: myvnc-volume
          mountPath: /app/my_vnc
        - name: lab304-db
          mountPath: /app/db.sqlite
      volumes:
      - name: myvnc-volume
        hostPath: 
          path: ~/LabServer/my_vnc
      - name: lab304-db
        hostPath: 
          path: ~/LabServer/OauthServer/db.sqlite
