---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db-svc
spec:
  selector:
    name: nextcloud-db-pod
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db-dep
spec:
  selector:
    matchLabels:
      name: nextcloud-db
  replicas: 1
  template:
    metadata:
      labels:
        name: nextcloud-db
    spec:
      containers:
      - name: nextcloud-db
        image: mariadb
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql_root_password
        - name: MYSQL_PASSWORD
          value: mysql_password
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: nextcloud-db-volume
      volumes:
      - name: nextcloud-db-volume
        hostPath: 
          path: ~/LabServer/Nextcloud/db1/
