---
apiVersion: v1
kind: Service
metadata:
  name: oauthserver
spec:
  selector:
    name: oauthserver
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver
spec:
  selector:
    matchLabels:
      name: oauthserver
  replicas: 1
  template:
    metadata:
      labels:
        name: oauthserver
    spec:
      containers:
      - name: oauthserver
        image: registry-svc.default.svc.cluster.local:5002/linnil1/oauthserver
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: volume
          mountPath: /app/OauthServer
          subPath: OauthServer
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: nfs-labserver
