apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-labserver
spec:
  storageClassName: nfs-labserver
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Ti
  nfs:
    server: {{ LABSERVER_IP }}
    path: {{ LABSERVER_PATH }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-labserver
spec:
  storageClassName: nfs-labserver
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
