apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-labserver
spec:
  storageClassName: nfs-labserver
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Ti
  nfs:
    server: {{ nfs.server_ip }}
    path: {{ nfs.server_path }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-labserver
spec:
  storageClassName: nfs-labserver
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Ti
