apiVersion: v1
kind: Namespace
metadata:
  name: user
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homenas
spec:
  storageClassName: nfs-homenas
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Ti
  nfs:
    server: {{ HOMENAS_IP }}
    path: {{ HOMENAS_PATH }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-homenas
  namespace: user
spec:
  storageClassName: nfs-homenas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-labnas
spec:
  storageClassName: nfs-labnas
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Ti
  nfs:
    server: {{ LABNAS_IP }}
    path: {{ LABNAS_PATH }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-labnas
  namespace: user
spec:
  storageClassName: nfs-labnas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
