apiVersion: v1
kind: Namespace
metadata:
  name: user
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homenas
spec:
  storageClassName: nfs-homenas
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Ti
  nfs:
    server: {{ nfs.home_ip }}
    path: {{ nfs.home_path }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-homenas
  namespace: user
spec:
  storageClassName: nfs-homenas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Ti
{% for nas in nfs.nas_shares %}
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ nas.name }}
spec:
  storageClassName: {{ nas.name }}
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Ti
  nfs:
    server: {{ nas.nas_ip }}
    path: {{ nas.nas_path }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ nas.name }}
  namespace: user
spec:
  storageClassName: {{ nas.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Ti
{% endfor %}
