externalIP: <ip>
rbac:
  enabled: true
dashboard:
  enabled: true

metrics:
  prometheus:
    enabled: true

kubernetes:
  namespaces:
  - default
  - kube-system
  - monitor
  ingressClass: traefik

ssl:
  enabled: true
  enforced: true
  insecureSkipVerify: true
  defaultCert: <cert>
  defaultKey: <key>
