externalIP: {{ external_ip }}
rbac:
  enabled: true
dashboard:
  enabled: true

metrics:
  prometheus:
    enabled: true

kubernetes:
  namespaces:
  - default
  - user
  - kube-system
  - monitor
  ingressClass: traefik

ssl:
  enabled: true
  enforced: true
  insecureSkipVerify: true
  defaultCert: null
  defaultKey: null
