version: 0.1
loglevel: debug
log:
  fields:
    service: registry

storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true

auth:
  token:
    realm: https://portus.default.svc.cluster.local/v2/token
    service: registry.default.svc.cluster.local
    issuer: portus.default.svc.cluster.local
    rootcertbundle: /certs/portus_cert.pem
# htpasswd:
#   realm: basic-realm
#   path: /certs/htpasswd

http:
  addr: :5000
  tls:
    certificate: /certs/cert.pem
    key: /certs/privkey.pem
  headers:
    X-Content-Type-Options: [nosniff]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

notifications:
  endpoints:
    - name: portus
      url: https://portus.default.svc.cluster.local/v2/webhooks/events
      timeout: 1000ms
      threshold: 5
      backoff: 5s
