# https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.yml
version: '3'
services:
  registry:
    image: registry:2.6
    command: ["/bin/sh", "/init_registry"]
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs:ro
      - ./config_registry.yml:/etc/docker/registry/config.yml:ro
      - ./init_registry:/init_registry:ro

  portus:
    image: opensuse/portus:2.4
    entrypoint: "/init_portus"
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECRET_KEY_BASE=${SECRETKEY}
      - PORTUS_PASSWORD=${SECRETKEY}
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_POOL=5
      - PORTUS_KEY_PATH=/certs/privkey.pem
      - RAILS_SERVE_STATIC_FILES='true'

      # SSL
      - PORTUS_PUMA_TLS_CERT=/certs/cert.pem
      - PORTUS_PUMA_TLS_KEY=/certs/privkey.pem
    ports:
      - 9992:3000
    external_links:
      - db
    volumes:
      - ./certs:/certs:ro
      - ./init_portus:/init_portus:ro
      
  background:
    image: opensuse/portus:2.4
    entrypoint: "/init_portus"
    environment:
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECRET_KEY_BASE=${SECRETKEY}
      - PORTUS_PASSWORD=${SECRETKEY}
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_POOL=5
      - PORTUS_KEY_PATH=/certs/privkey.pem
      - PORTUS_BACKGROUND=true
    external_links:
      - db
    volumes:
      - ./certs:/certs:ro
      - ./init_portus:/init_portus:ro

  db:
    image: library/mariadb:10.4
    environment:
      - MYSQL_DATABASE=portus_production
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
